version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  web:
    container_name: django
    build: ./dockerfiles/django_docker/
    command: python3 futsal_django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    # front:
    #   container_name: nuxt
    #   build: ./dockerfiles/nuxt_docker/
    #   tty: true
    #   working_dir: /workspace/
    # command: yarn run dev
    # volumes:
    #   - ./nuxt:/workspace
    # ports:
    #   - "3000:3000"
