version: '3'
services:
  db:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    restart: always
  web:
    container_name: django
    build: ./dockerfiles/django_docker/
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    # front:
    #   container_name: nuxt
    #   build: ./dockerfiles/nuxt_docker/
    #   tty: true
    #   working_dir: /workspace/
    # command: yarn run dev
    # volumes:
    #   - ./nuxt:/workspace
    # ports:
    #   - "3000:3000"
