# Generated by Django 4.0.2 on 2022-02-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='（例）東京工業大学フットサル部 Tokyo Tech', max_length=32, verbose_name='チーム名')),
                ('homepage_url', models.URLField(verbose_name='ホームページ（URL）')),
            ],
            options={
                'verbose_name': 'チーム',
                'verbose_name_plural': 'チーム',
                'db_table': 'club',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='(例) 森岡', max_length=32, verbose_name='苗字（漢字）')),
                ('first_name', models.CharField(help_text='（例）薫', max_length=32, verbose_name='名前（漢字）')),
                ('uniform_number', models.IntegerField(help_text='所属チームでの背番号', verbose_name='背番号')),
                ('birth_day', models.DateField(help_text='（例）1998-06-22', verbose_name='誕生日')),
                ('position', models.IntegerField(choices=[(1, 'フィクソ（FIXO）'), (2, 'アラ（ALA）'), (3, 'ピヴォ（PIVO）'), (4, 'ゴレイロ（GOLEIRO）')], verbose_name='ポジション')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.club')),
            ],
            options={
                'verbose_name': '選手',
                'verbose_name_plural': '選手',
                'db_table': 'player',
                'ordering': ['birth_day'],
            },
        ),
    ]
