# Generated by Django 4.0.4 on 2022-04-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='カテゴリー名')),
                ('part_number', models.IntegerField(help_text='２部リーグ→2', verbose_name='部数')),
            ],
            options={
                'verbose_name_plural': 'カテゴリー',
                'db_table': 'category',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='（例）東京工業大学フットサル部 Tokyo Tech', max_length=32, verbose_name='チーム名')),
                ('homepage_url', models.URLField(blank=True, null=True, verbose_name='ホームページ（URL）')),
            ],
            options={
                'verbose_name_plural': 'チーム',
                'db_table': 'club',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='キックオフ時刻')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='match.club', verbose_name='アウェイチーム')),
            ],
            options={
                'verbose_name_plural': '試合',
                'db_table': 'game',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='リーグ名')),
                ('teams', models.ManyToManyField(to='match.club')),
            ],
            options={
                'verbose_name_plural': 'リーグ',
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'プレイヤー'), (2, 'スタッフ'), (3, 'スタッフ兼プレイヤー')], verbose_name='種類')),
                ('last_name', models.CharField(help_text='(例) 森岡', max_length=32, verbose_name='苗字（漢字）')),
                ('first_name', models.CharField(help_text='（例）薫', max_length=32, verbose_name='名前（漢字）')),
                ('uniform_number', models.IntegerField(help_text='所属チームでの背番号', verbose_name='背番号')),
                ('birth_day', models.DateField(blank=True, help_text='（例）1998-06-22', null=True, verbose_name='誕生日')),
                ('position', models.IntegerField(choices=[(1, 'フィクソ（FIXO）'), (2, 'アラ（ALA）'), (3, 'ピヴォ（PIVO）'), (4, 'ゴレイロ（GOLEIRO）')], verbose_name='ポジション')),
                ('profile', models.TextField(blank=True, null=True, verbose_name='プロフィール')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.club')),
            ],
            options={
                'verbose_name_plural': '選手',
                'db_table': 'member',
                'ordering': ['birth_day'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名前')),
                ('address', models.TextField(verbose_name='住所')),
            ],
            options={
                'verbose_name_plural': '場所',
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='(例) 森岡', max_length=32, verbose_name='苗字（漢字）')),
                ('first_name', models.CharField(help_text='（例）薫', max_length=32, verbose_name='名前（漢字）')),
            ],
            options={
                'verbose_name_plural': '審判',
                'db_table': 'referee',
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='時間')),
                ('half', models.BooleanField(choices=[(False, '前半'), (True, '後半')], verbose_name='前半or後半')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.member')),
            ],
            options={
                'verbose_name_plural': '警告',
                'db_table': 'warning',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.game')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.member')),
            ],
            options={
                'verbose_name_plural': '役員（スタッフ）',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half', models.BooleanField(choices=[(False, '前半'), (True, '後半')], verbose_name='前半or後半')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.member')),
            ],
            options={
                'verbose_name_plural': 'シュート',
                'db_table': 'shoot',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='シーズン名')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.league')),
            ],
            options={
                'verbose_name_plural': 'シーズン',
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='RegisteredMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_member', models.BooleanField(choices=[(False, 'ベンチ'), (True, '先発')], verbose_name='先発orベンチ')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.member')),
            ],
            options={
                'verbose_name_plural': '登録メンバー',
                'db_table': 'registered_member',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='節')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.category')),
            ],
            options={
                'verbose_name_plural': '節',
                'db_table': 'node',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='時間')),
                ('half', models.BooleanField(choices=[(False, '前半'), (True, '後半')], verbose_name='前半or後半')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.member')),
            ],
            options={
                'verbose_name_plural': 'ゴール',
                'db_table': 'goal',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='first_referee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='first_referee', to='match.referee'),
        ),
        migrations.AddField(
            model_name='game',
            name='goals',
            field=models.ManyToManyField(related_name='goals', through='match.Goal', to='match.member'),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='match.club', verbose_name='ホームチーム'),
        ),
        migrations.AddField(
            model_name='game',
            name='members',
            field=models.ManyToManyField(related_name='members', through='match.RegisteredMember', to='match.member'),
        ),
        migrations.AddField(
            model_name='game',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.node', verbose_name='節'),
        ),
        migrations.AddField(
            model_name='game',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.place', verbose_name='場所'),
        ),
        migrations.AddField(
            model_name='game',
            name='second_referee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='second_referee', to='match.referee'),
        ),
        migrations.AddField(
            model_name='game',
            name='shoots',
            field=models.ManyToManyField(related_name='shoots', through='match.Shoot', to='match.member'),
        ),
        migrations.AddField(
            model_name='game',
            name='staffs',
            field=models.ManyToManyField(related_name='staffs', through='match.Staff', to='match.member'),
        ),
        migrations.AddField(
            model_name='game',
            name='third_referee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='third_referee', to='match.referee'),
        ),
        migrations.AddField(
            model_name='game',
            name='warnings',
            field=models.ManyToManyField(related_name='warnings', through='match.Warning', to='match.member'),
        ),
        migrations.AddField(
            model_name='category',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.season'),
        ),
    ]
