# Generated by Django 4.0.1 on 2022-02-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_player_options_remove_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(choices=[(1, 'FIXO'), (2, 'ALA'), (3, 'PIVO'), (4, 'GOLEIRO')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_day',
            field=models.DateField(help_text='（例）1998-06-22', verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(help_text='（例）薫', max_length=32, verbose_name='名前（漢字）'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(help_text='(例) 森岡', max_length=32, verbose_name='苗字（漢字）'),
        ),
        migrations.AlterField(
            model_name='player',
            name='uniform_number',
            field=models.IntegerField(help_text='所属チームでの背番号', verbose_name='背番号'),
        ),
    ]
