# Generated by Django 4.0.1 on 2022-02-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_player_position_alter_player_birth_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='（例）東京工業大学フットサル部 Tokyo Tech', max_length=32, verbose_name='チーム名')),
                ('homepage_url', models.URLField(verbose_name='ホームページ（URL）')),
            ],
            options={
                'verbose_name': 'チーム',
                'verbose_name_plural': 'チーム',
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(choices=[(1, 'フィクソ（FIXO）'), (2, 'アラ（ALA）'), (3, 'ピヴォ（PIVO）'), (4, 'ゴレイロ（GOLEIRO）')], verbose_name='ポジション'),
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='match.club'),
            preserve_default=False,
        ),
    ]
